name: covid19
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^0.7.1+1
  audioplayers: ^0.14.2
  url_launcher: ^5.4.2
  flare_flutter: ^2.0.1
  flare_splash_screen: ^2.0.1+2
  rxdart: ^0.22.0
  http: ^0.12.0+2
  date_format: ^1.0.8
  pull_to_refresh: ^1.5.7
  charts_flutter: ^0.9.0
  google_fonts: ^0.3.10
  intl: ^0.16.1
  flutter_share: ^1.0.2+1
  shared_preferences: ^0.5.6+3
  firebase_auth: ^0.15.5+3
  simple_animations: ^1.3.11
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.3.0
  provider_architecture: ^1.0.6
  firebase_admob: ^0.9.3+1
  google_maps_flutter: ^0.5.25+2
  firebase_messaging:
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/splash.flr
    - assets/meditation.flr
    - assets/arc.flr
    - assets/women.png
    - assets/women2.png
    - assets/women3.png
    - assets/Map.png
    - assets/Cards/Cont1.png
    - assets/Cards/Cont2.png
    - assets/Cards/Cont3.png
    - assets/Cards/Cont4.png
    - assets/Cards/Prev1.png
    - assets/Cards/Prev2.png
    - assets/Cards/Prev3.png
    - assets/Cards/Prev4.png
    - assets/Cards/Symp1.png
    - assets/Cards/Symp2.png
    - assets/Cards/Symp3.png
    - assets/Cards/Symp4.png
    - assets/Donate.png
    - assets/PlainMap.png
    - assets/loadingPage.png
    - assets/feedLoading.png
    - assets/donateWHO.png
    - assets/donatePMcares.png
    - assets/donateAmericares.png
    - assets/donateDR.png
    - assets/map_style.txt
    - assets/strongGirl.png
    - assets/people.png
    - assets/washHands.jpg
    - assets/preventions.jpg
    - assets/helpBy5.jpg
    - assets/stressed.png
    - assets/helpline.png
    - assets/share.png
    - assets/drinking.png
    - assets/noPanic.png
    - assets/basic.png
    - assets/medilines.png
    - assets/mediplus.png
    - assets/medihexa.png
    - assets/medibubble.png
    - assets/medistar.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AjayisticIcons
      fonts:
        - asset: fonts/AjayisticIcons.ttf
    - family: Glinticons
      fonts:
        - asset: fonts/Glinticons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Shine
      fonts:
        - asset: fonts/Shine.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages